import { Octokit } from '@octokit/rest'
import prisma from '../lib/prisma'
import { encrypt, decrypt } from '../lib/crypto'
import * as scaffold from '../lib/scaffold'
import { generatePRDescription } from './gemini.service'
import { RepoConflictError } from '../lib/errors'

function toBase64(content: string): string {
  return Buffer.from(content, 'utf8').toString('base64')
}

// ─── OAuth ───────────────────────────────────────────────────────────────────

export async function exchangeCodeForToken(
  code: string,
): Promise<{ accessToken: string; login: string }> {
  const tokenRes = await fetch('https://github.com/login/oauth/access_token', {
    method: 'POST',
    headers: { Accept: 'application/json', 'Content-Type': 'application/json' },
    body: JSON.stringify({
      client_id: process.env.GITHUB_CLIENT_ID,
      client_secret: process.env.GITHUB_CLIENT_SECRET,
      code,
    }),
  })

  const tokenData = (await tokenRes.json()) as { access_token?: string; error?: string }
  if (!tokenData.access_token) throw new Error(tokenData.error ?? 'OAuth exchange failed')

  const userRes = await fetch('https://api.github.com/user', {
    headers: {
      Authorization: `Bearer ${tokenData.access_token}`,
      Accept: 'application/vnd.github.v3+json',
    },
  })
  const user = (await userRes.json()) as { login: string }

  return { accessToken: tokenData.access_token, login: user.login }
}

export async function saveGithubConnection(
  userId: string,
  accessToken: string,
  login: string,
): Promise<void> {
  const encryptedToken = encrypt(accessToken)
  await prisma.githubConnection.upsert({
    where: { userId },
    update: { accessToken: encryptedToken, githubUsername: login, revokedAt: null },
    create: { userId, accessToken: encryptedToken, githubUsername: login, scope: 'repo' },
  })
}

export async function getDecryptedToken(
  userId: string,
): Promise<{ token: string; login: string } | null> {
  const connection = await prisma.githubConnection.findUnique({ where: { userId } })
  if (!connection || connection.revokedAt) return null
  return { token: decrypt(connection.accessToken), login: connection.githubUsername }
}

export async function getConnectionStatus(
  userId: string,
): Promise<{ connected: boolean; username?: string }> {
  const connection = await prisma.githubConnection.findUnique({ where: { userId } })
  if (!connection || connection.revokedAt) return { connected: false }
  return { connected: true, username: connection.githubUsername }
}

// ─── Repository operations ───────────────────────────────────────────────────

export async function createRepository(
  token: string,
  name: string,
  isPrivate: boolean,
): Promise<{ fullName: string }> {
  const octokit = new Octokit({ auth: token })
  try {
    const { data } = await octokit.repos.createForAuthenticatedUser({
      name,
      private: isPrivate,
      description: 'Design system generated by SuperDSAI Generator',
      auto_init: false,
    })
    return { fullName: data.full_name }
  } catch (err: unknown) {
    if ((err as { status?: number }).status === 422) {
      throw new RepoConflictError(`${name}-2`)
    }
    throw err
  }
}

export async function scaffoldRepository(
  token: string,
  fullName: string,
  colors: Record<string, string>,
  typography: Record<string, unknown>,
  componentCode: string,
  repoName: string,
): Promise<void> {
  const octokit = new Octokit({ auth: token })
  const [owner, repo] = fullName.split('/')

  const files: { path: string; content: string }[] = [
    { path: 'package.json', content: scaffold.buildPackageJson(repoName) },
    { path: '.storybook/main.js', content: scaffold.buildStorybookMain() },
    { path: '.storybook/preview.js', content: scaffold.buildStorybookPreview() },
    { path: 'src/index.css', content: scaffold.buildIndexCss() },
    { path: 'src/tokens/colors.json', content: scaffold.buildColorsJson(colors) },
    { path: 'src/tokens/typography.json', content: scaffold.buildTypographyJson(typography) },
    { path: 'tailwind.config.js', content: scaffold.buildTailwindConfig(colors) },
    { path: 'postcss.config.js', content: scaffold.buildPostcssConfig() },
    { path: 'vercel.json', content: scaffold.buildVercelConfig() },
    { path: 'src/components/Button.jsx', content: componentCode },
    { path: 'src/components/Button.stories.jsx', content: scaffold.buildButtonStories() },
  ]

  for (const file of files) {
    await octokit.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: file.path,
      message: 'chore: initial design system scaffold',
      content: toBase64(file.content),
    })
  }
}

export async function createUpdatePR(
  token: string,
  fullName: string,
  colors: Record<string, string>,
  typography: Record<string, unknown>,
  componentCode: string,
  dsName: string,
): Promise<{
  prNumber: number
  prUrl: string
  branchName: string
  prTitle: string
  prBody: string
}> {
  const octokit = new Octokit({ auth: token })
  const [owner, repo] = fullName.split('/')

  const { data: mainBranch } = await octokit.repos.getBranch({ owner, repo, branch: 'main' })
  const mainSha = mainBranch.commit.sha
  const branchName = `ds-update-${Date.now()}`

  await octokit.git.createRef({ owner, repo, ref: `refs/heads/${branchName}`, sha: mainSha })

  const filesToUpdate = [
    { path: 'src/tokens/colors.json', content: scaffold.buildColorsJson(colors) },
    { path: 'src/tokens/typography.json', content: scaffold.buildTypographyJson(typography) },
    { path: 'tailwind.config.js', content: scaffold.buildTailwindConfig(colors) },
    { path: 'src/components/Button.jsx', content: componentCode },
  ]

  for (const file of filesToUpdate) {
    let currentSha: string | undefined
    try {
      const { data: existing } = await octokit.repos.getContent({
        owner, repo, path: file.path, ref: branchName,
      })
      if ('sha' in existing) currentSha = existing.sha
    } catch { /* new file */ }

    await octokit.repos.createOrUpdateFileContents({
      owner, repo,
      path: file.path,
      message: `update: ${file.path}`,
      content: toBase64(file.content),
      branch: branchName,
      ...(currentSha ? { sha: currentSha } : {}),
    })
  }

  const { title: prTitle, body: prBody } = await generatePRDescription({
    changedTokenKeys: Object.keys(colors),
    hasComponentChanges: true,
    dsName,
  })

  const { data: pr } = await octokit.pulls.create({
    owner, repo, title: prTitle, body: prBody, head: branchName, base: 'main',
  })

  return { prNumber: pr.number, prUrl: pr.html_url, branchName, prTitle, prBody }
}
